name: Build & Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

#    services:
#      postgres:
#        image: postgres
#        env:
#          POSTGRES_USER: app
#          POSTGRES_PASSWORD: password
#          POSTGRES_NAME: app
#        # Set health checks to wait until postgres has started
#        options: >-
#          --health-cmd pg_isready
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5
#        ports:
#          - 5432:5432

    env:
      ROLLBAR_TOKEN: ${{ secrets.ROLLBAR_TOKEN }}

    steps:
      - uses: actions/setup-go@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Download dependencies
        run: go get
      - name: Build the application
        run: go build -o app
      - name: Install
        run: make install
      - name: Initialize Terraform
        run: terraform init
        working-directory: ./example
      - name: Terraform plan
        run: terraform plan -var 'rollbar_token=${{ secrets.ROLLBAR_TOKEN }}'
        working-directory: ./example
        env:
          ROLLBAR_TOKEN: ${{ secrets.ROLLBAR_TOKEN }}
      - name: Unit tests
        run: make test
      - name: Acceptance tests
        run: make testacc
